blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/contentful/contentful-import/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/contentful/contentful-import/blob/main/README.md
    about: Check out our documentation for help and guides
